#!/bin/bash -e

# Stop the service, if running
if status mongo-mms-agent | grep -q 'running'
then
    stop mongo-mms-agent
fi


# Remove anything from /var/run/mongo-mms-agent/
rm -rf /var/run/mongo-mms-agent/*

# Remove .pyc files so apt will remove empty /opt/mongo-mms-agent
rm -f /opt/mongo-mms-agent/*.pyc

